//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education.Implementation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Professor
    {
        public long ProfessorID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public long ClassMstID { get; set; }
    
        public virtual ClassMst ClassMst { get; set; }
    }
}
